### ISSUE TITLE
Modernization

### ISSUE THREAD

**Issue by Maxime-J** [Infomaniak/kpaste#11]
Would you be interested in a modernization?

kPaste uses quite a few old/deprecated/legacy stuff now:
-React class components
-node-sass
-Material UI v4
-React Router v5
-some Babel plugins

Addressing this with slight changes here and there would give kPaste a cleaner look codewise.

That's something I'd like to work on if wanted,
and unless it's planned internally / you'd prefer doing it yourself.

I could probably send a PR within a month.

**Comment by L3o-pold** [comment]
I think it's an internal work to be due someday. 
Thanks for the proposal though.

**Comment by Maxime-J** [comment]
Ok, fine. I'll join Infomaniak to be assigned with this one day :wink:
Kidding aside, this is something I will do anyway for me, so I would gladly share if you change your mind.

**Comment by L3o-pold** [comment]
@Maxime-J FYI the work already started on our side

**Comment by L3o-pold** [comment]
And of course, you are welcome to check open positions if interested: https://www.infomaniak.com/en/about/career
