### ISSUE TITLE
Possibilité d'ajouter une API pour l'envoie de message

### ISSUE THREAD

**Issue by bdrayersyno** [Infomaniak/kpaste#8]
Bonjour,

J'utilise très fréquement votre logiciel pour envoyer des mots de passes ou des informations confidentielles à mes utilisateurs et j'aurais voulu savoir si il était possible d'ajouter une API permettant l'envoie de messages depuis une application tierce (dans mon cas la gestion des utilisateurs) afin de me permettre d'automatiser l'envoie du mot de passe plutôt que de devoir faire un copier et coller dans l'interface web.

Merci d'avance

**Comment by L3o-pold** [comment]
Non car il y a un chiffrement end to end qui est fait coté browser (client).
