### ISSUE TITLE
vendor.js size

### ISSUE THREAD

**Issue by Maxime-J** [Infomaniak/kpaste#9]
I was surprised by the bundle size while playing with kPaste.

If it's relevant to you, turns out syntax highlighting is taking a lot of space:

![big](https://github.com/Infomaniak/kpaste/assets/12450219/7401c022-be53-4a74-a8ca-2f55f3acad02)

65% of a ~440 KB gzipped vendor.js
that's huge for a feature (probably?) used a very few times.

I removed that code feature
but otherwise, footprint can be fairly reduced by loading only the most commonly used languages (in lib/CodeHighlight.jsx):
```
import hljs from 'highlight.js/lib/common';
```
=> 22% of a ~195 KB gzipped vendor.js

![smaller](https://github.com/Infomaniak/kpaste/assets/12450219/1b23da25-1bb9-439c-b56f-b0ff82d53780)

**Comment by L3o-pold** [comment]
Thanks for the feedback. Feel free to open a PR for loading only the most commonly used language.

**Comment by Maxime-J** [comment]
Thanks for the quick reply 👍 
PR is submitted.
